task: S2G
data:
  input_data: videos #features, gloss
  input_streams:
    - keypoint
    - rgb
  #keypoint_file: ../../data/phoenix-2014/phoenix-2014-keypoints.pkl
  keypoint_file: /nas/Dataset/Phoenix/phoenix-2014-keypoints.pkl
  use_keypoints:
    - pose 
    - mouth_half
    - hand
    - face_others_1_3
  # zip_file: ../../data/phoenix-2014/phoenix-2014-videos.zip
  # train: ../../data/phoenix-2014/phoenix-2014.train
  # dev: ../../data/phoenix-2014/phoenix-2014.dev
  # test: ../../data/phoenix-2014/phoenix-2014.test
  zip_file: /nas/Dataset/Phoenix/phoenix-2014-videos.zip
  train: data/phoenix-2014/phoenix-2014.train
  dev: data/phoenix-2014/phoenix-2014.dev
  test: data/phoenix-2014/phoenix-2014.test  
  dataset_name: phoenix-2014 
  level: word #word or char
  txt_lowercase: true
  max_sent_length: 400
  transform_cfg:
    img_size: 224
    color_jitter: true
    bottom_area: 0.7 
    center_crop_size: 224 
    center_crop: False
    randomcrop_threshold: 1
    aspect_ratio_min: 0.75
    aspect_ratio_max: 1.3
    temporal_augmentation:
      tmin: 0.5
      tmax: 1.5
testing:
  cfg:
    recognition:
      beam_size: 5
training:
  #from_ckpt: True  # Enable resume functionality
  #overwrite: False
  overwrite: True
  model_dir: results/phoenix-2014-doppler-vectorized+s2g
  random_seed: 0
  shuffle: True
  num_workers: 4
  batch_size: 2
  total_epoch: 40
  keep_last_ckpts: 5
  validation: 
    unit: epoch
    freq: 1
    cfg:
      recognition:
        beam_size: 1
  optimization:
    optimizer: Adam
    learning_rate:
      default: 1.0e-3
    weight_decay: 0.001
    betas:
    - 0.9
    - 0.998
    scheduler: cosineannealing
    t_max: 40
model:
  RecognitionNetwork:
    #pretrained_path_rgb: results/phoenix-2014_video2/ckpts/best.ckpt # results/phoenix-2014_s2g
    #pretrained_path_keypoint: results/phoenix-2014_keypoint2/ckpts/best.ckpt # results/phoenix-2014_s2g DONE WER= 21.57
    
    #pretrained_path_rgb: results/phoenix-2014_s2g/ckpts/best.ckpt # results/phoenix-2014_s2g_vec
    #pretrained_path_keypoint: results/phoenix-2014_keypoint_vector/ckpts/best.ckpt #results/phoenix-2014_s2g_vec DONE WER=24.7 
    
    #pretrained_path_rgb: results/phoenix-2014_s2g/ckpts/best.ckpt # results/phoenix-2014_s2g_vec2
    #pretrained_path_keypoint: results/phoenix-2014_keypoint_vector2/ckpts/best.ckpt #results/phoenix-2014_s2g_vec2 DONE WER= 24.7
    
    #pretrained_path_rgb: results/phoenix-2014_s2g/ckpts/best.ckpt # results/phoenix-2014_s2g_diff
    #pretrained_path_keypoint: results/phoenix-2014-keypoints-diff/ckpts/best.ckpt #results/phoenix-2014_s2g_diff DONE WER=24.7
    
    #pretrained_path_rgb: results/phoenix-2014_s2g/ckpts/best.ckpt # results/phoenix-2014_s2g_diff_cleaned
    #pretrained_path_keypoint: results/phoenix-2014-keypoints-diff-cleaned/ckpts/best.ckpt #results/phoenix-2014_s2g_diff_cleaned DONE WER=25.17 
    
    pretrained_path_rgb: results/phoenix-2014_s2g/ckpts/best.ckpt 
    pretrained_path_keypoint: results/phoenix-2014-doppler-vectorized/ckpts/best.ckpt 
    
    
    
    
    GlossTokenizer:
      lower_case: False
      #gloss2id_file: ../../data/phoenix-2014/gloss2ids.pkl
      gloss2id_file: data/phoenix-2014/gloss2ids.pkl
    s3d:
      #pretrained_ckpt: ../../pretrained_models/s3ds_actioncls_ckpt #from K400
      pretrained_ckpt: pretrained_models/s3ds_actioncls_ckpt #from K400
      use_block: 4
      freeze_block: 1
    keypoint_s3d:
      in_channel: 0 # placeholder
      #pretrained_ckpt: ../../pretrained_models/s3ds_actioncls_ckpt #from K400
      pretrained_ckpt: pretrained_models/s3ds_actioncls_ckpt #from K400
      use_block: 4
      freeze_block: 0
    heatmap_cfg:
      raw_size:
        - 260
        - 210 
      input_size: 112
      sigma: 8
    fuse_method: triplehead_cat_bilateral
    lateral:
      pose2rgb: true
      rgb2pose: true
      variant_pose2rgb: null
      variant_rgb2pose: null
      fusion_features:
        - c1
        - c2
        - c3
        - c4
        
    pyramid:
      version: v1
      rgb: multi_head #shared_head #s3d_pooled_plus #pose_fused
      pose: multi_head #shared_head #s3d_pooled_plus #pose_fused
      head_weight_rgb: 0.2
      head_weight_keypoint: 0.5
      num_levels: 3
    visual_head:
      input_size: 832
      hidden_size: 512
      ff_size: 2048 
      pe: True 
      ff_kernelsize:
        - 3
        - 3
    cross_distillation:
      teacher_detach: True
      types:
        ensemble_last_teaches_keypoint: 1
        ensemble_last_teaches_rgb: 1
        ensemble_last_teaches_fuse: 1




